/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sparepartsnew.ui.modules;


import javax.swing.JOptionPane;
import sparepartsnew.service.impl.HistoryServiceImpl;
import sparepartsnew.service.impl.ModulServiceImpl;
import sparepartsnew.service.impl.UsersServiceImpl;
import sparepartsnew.model.Sort;
import sparepartsnew.ui.component.tablemodel.HistoryTableModel;

/**
 *
 * @author Marko HP
 */
public class HistoryViewForm extends javax.swing.JDialog {

    private HistoryServiceImpl historyRepo;
    private ModulServiceImpl modulRepo;
    private UsersServiceImpl userRepo;
    
    
    public HistoryViewForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        historyRepo = new HistoryServiceImpl();
        modulRepo = new ModulServiceImpl();
        userRepo = new UsersServiceImpl();
        initComponents();        
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("History of modules");

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblHistory);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSort.setText("Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addGap(18, 18, 18)
                        .addComponent(btnSort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnSort)
                    .addComponent(btnCancel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
     prepareForm();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
       int selectedColumn = tblHistory.getSelectedColumn();
      
      switch (selectedColumn) {
           case 0: 
            HistoryTableModel dtm0 = new HistoryTableModel(Sort.id);
            tblHistory.setModel(dtm0);
           break;
           case 1: 
            HistoryTableModel dtm1 = new HistoryTableModel(Sort.modul_id);
            tblHistory.setModel(dtm1);
           break;
           case 2: 
            HistoryTableModel dtm2 = new HistoryTableModel(Sort.username);
            tblHistory.setModel(dtm2);
           break;           
           case 3: 
            HistoryTableModel dtm3 = new HistoryTableModel(Sort.operation);
            tblHistory.setModel(dtm3);
           break;
           case 4: 
            HistoryTableModel dtm4 = new HistoryTableModel(Sort.date_time);
            tblHistory.setModel(dtm4);
           break;          
           default:
               JOptionPane.showMessageDialog(this,"Error", "Column not selected for sorting!", JOptionPane.ERROR_MESSAGE);
               break;
    }
    }//GEN-LAST:event_btnSortActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistory;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        HistoryTableModel dtm = new HistoryTableModel(Sort.id);
        tblHistory.setModel(dtm);
    }
}
