/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sparepartsnew.ui.modules;


import javax.swing.JOptionPane;
import sparepartsnew.model.Users;
import sparepartsnew.service.impl.LocationServiceImpl;
import sparepartsnew.model.Sort;
import sparepartsnew.ui.component.tablemodel.LocationsTableModel;

/**
 *
 * @author Marko HP
 */
public class LocationsViewForm extends javax.swing.JFrame {
    
    private LocationServiceImpl locationRepo;
    private Users user;
    
    public LocationsViewForm(Users user) {
        initComponents();
        this.user=user;
        prepareForm();
        locationRepo = new LocationServiceImpl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLocations = new javax.swing.JTable();
        btnNewLocation = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Locations");

        tblLocations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblLocations);

        btnNewLocation.setText("New location");
        btnNewLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewLocationActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSort.setText("Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh)
                        .addGap(26, 26, 26)
                        .addComponent(btnSort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewLocation)
                    .addComponent(btnCancel)
                    .addComponent(btnRefresh)
                    .addComponent(btnSort))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnNewLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewLocationActionPerformed
        new LocationAddForm(this, true, user).setVisible(true);
    }//GEN-LAST:event_btnNewLocationActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       prepareForm();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
      int selectedColumn = tblLocations.getSelectedColumn();
      
      switch (selectedColumn) {
           case 0: 
            LocationsTableModel dtm0 = new LocationsTableModel(Sort.site_code);
            tblLocations.setModel(dtm0);
           break;
           case 1: 
            LocationsTableModel dtm1 = new LocationsTableModel(Sort.name);
            tblLocations.setModel(dtm1);
           break;
           case 2: 
            LocationsTableModel dtm2 = new LocationsTableModel(Sort.type);
            tblLocations.setModel(dtm2);
           break;           
           case 3: 
            LocationsTableModel dtm3 = new LocationsTableModel(Sort.address);
            tblLocations.setModel(dtm3);
           break;
           case 4: 
            LocationsTableModel dtm4 = new LocationsTableModel(Sort.lat);
            tblLocations.setModel(dtm4);
           break;
           case 5: 
            LocationsTableModel dtm5 = new LocationsTableModel(Sort.lon);
            tblLocations.setModel(dtm5);
           break;
           
           default:
               JOptionPane.showMessageDialog(this,"Error", "Column not selected for sorting!", JOptionPane.ERROR_MESSAGE);
               break;
    }
    }//GEN-LAST:event_btnSortActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNewLocation;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLocations;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        
        LocationsTableModel dtm = new LocationsTableModel(Sort.site_code);
        tblLocations.setModel(dtm);           
    }
}
