/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sparepartsnew.ui.modules;

import java.util.List;
import javax.swing.JOptionPane;
import sparepartsnew.model.Sort;
import sparepartsnew.model.Location;
import sparepartsnew.model.Modul;
import sparepartsnew.model.Status;
import sparepartsnew.model.Users;

import sparepartsnew.service.impl.LocationServiceImpl;
import sparepartsnew.service.impl.ModulServiceImpl;

/**
 *
 * @author Marko HP
 */
public class ModulesEditedForm extends javax.swing.JDialog {

    private Modul modul;
    private LocationServiceImpl locationRepository;
    private ModulServiceImpl modulRepository;
    private Users user;
    
    public ModulesEditedForm(java.awt.Frame parent, boolean modal, Modul modul, Users user) throws Exception {
        super(parent, modal);
        this.modul=modul;
        this.user=user;
        locationRepository=new LocationServiceImpl();
        modulRepository=new ModulServiceImpl();
        initComponents();
        fillCombo();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupStatus = new javax.swing.ButtonGroup();
        groupType = new javax.swing.ButtonGroup();
        lblModule = new javax.swing.JLabel();
        txtModule = new javax.swing.JTextField();
        lblSn = new javax.swing.JLabel();
        txtSn = new javax.swing.JTextField();
        lblPn = new javax.swing.JLabel();
        txtPn = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        radioOperative = new javax.swing.JRadioButton();
        radioFaulty = new javax.swing.JRadioButton();
        radioTest = new javax.swing.JRadioButton();
        lblType = new javax.swing.JLabel();
        radioRadio = new javax.swing.JRadioButton();
        radioTransport = new javax.swing.JRadioButton();
        radioPower = new javax.swing.JRadioButton();
        radioAsset = new javax.swing.JRadioButton();
        lblLocation = new javax.swing.JLabel();
        comboLocation = new javax.swing.JComboBox<>();
        btnNewLocation = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblMM = new javax.swing.JLabel();
        txtMM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit module");

        lblModule.setText("Module to edit:");

        txtModule.setEditable(false);
        txtModule.setText(" ");

        lblSn.setText("S/N:");

        txtSn.setEditable(false);
        txtSn.setText(" ");

        lblPn.setText("P/N:");

        txtPn.setEditable(false);
        txtPn.setText(" ");

        lblStatus.setText("Status:");

        groupStatus.add(radioOperative);
        radioOperative.setText("Operative");

        groupStatus.add(radioFaulty);
        radioFaulty.setText("Faulty");

        groupStatus.add(radioTest);
        radioTest.setText("Test");

        lblType.setText("Type:");

        groupType.add(radioRadio);
        radioRadio.setText("Radio");

        groupType.add(radioTransport);
        radioTransport.setText("Transport");

        groupType.add(radioPower);
        radioPower.setText("Power");

        groupType.add(radioAsset);
        radioAsset.setText("Asset");

        lblLocation.setText("Location:");

        btnNewLocation.setText("New location");
        btnNewLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewLocationActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblMM.setText("MM:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblModule, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtModule))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioTransport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioPower)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioAsset))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioOperative)
                                .addGap(18, 18, 18)
                                .addComponent(radioFaulty)
                                .addGap(38, 38, 38)
                                .addComponent(radioTest))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnNewLocation))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMM, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPn, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(txtMM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModule, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioOperative)
                        .addComponent(radioFaulty)
                        .addComponent(radioTest)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioRadio)
                    .addComponent(radioTransport)
                    .addComponent(radioPower)
                    .addComponent(radioAsset))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNewLocation)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Modul updatedModul=new Modul();
        String name = txtModule.getText();
        String sn = txtSn.getText().trim();
        String pn = txtPn.getText().trim();
        int mm = Integer.parseInt(txtMM.getText());
        Status status = null;
        
        if (radioOperative.isSelected()) status=Status.Operative;
        else if (radioFaulty.isSelected()) status =Status.Faulty;
        else status=Status.Test;
        
        sparepartsnew.model.Type type = null;
        
        if (radioRadio.isSelected()) type=sparepartsnew.model.Type.Radio;
        else if (radioTransport.isSelected()) type=sparepartsnew.model.Type.Transport;
        else if (radioPower.isSelected()) type=sparepartsnew.model.Type.Power;
        else type=sparepartsnew.model.Type.Asset;
         
        try {
            Location location =(Location) comboLocation.getSelectedItem();
        
        updatedModul=new Modul(modul.getId(),name, sn, pn, mm, type, location, status);
            modulRepository.edit(updatedModul, user);
            JOptionPane.showMessageDialog(this, "Successfull operation", "You have successfully edited a module",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
           ex.printStackTrace();
           JOptionPane.showMessageDialog(this, "Operation failed", "Module is not edited!",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewLocationActionPerformed
        new LocationAddForm(null, true, user).setVisible(true);
    }//GEN-LAST:event_btnNewLocationActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNewLocation;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Location> comboLocation;
    private javax.swing.ButtonGroup groupStatus;
    private javax.swing.ButtonGroup groupType;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMM;
    private javax.swing.JLabel lblModule;
    private javax.swing.JLabel lblPn;
    private javax.swing.JLabel lblSn;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblType;
    private javax.swing.JRadioButton radioAsset;
    private javax.swing.JRadioButton radioFaulty;
    private javax.swing.JRadioButton radioOperative;
    private javax.swing.JRadioButton radioPower;
    private javax.swing.JRadioButton radioRadio;
    private javax.swing.JRadioButton radioTest;
    private javax.swing.JRadioButton radioTransport;
    private javax.swing.JLabel txtMM;
    private javax.swing.JTextField txtModule;
    private javax.swing.JTextField txtPn;
    private javax.swing.JTextField txtSn;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() throws Exception {
       txtModule.setText(modul.getId()+" "+modul.getName());
       txtSn.setText(modul.getSn());
       txtPn.setText(modul.getPn());
       switch (modul.getStatus()) {
           case Operative:
               radioOperative.setSelected(true);
               break;
           case Faulty:
               radioFaulty.setSelected(true);
               break;
           case Test:
               radioTest.setSelected(true);
               break;
       }
       switch (modul.getType()) {
           case Radio:
               radioRadio.setSelected(true);
               break;
           case Transport:
               radioTransport.setSelected(true);
               break;
           case Power:
               radioPower.setSelected(true);
               break;
           case Asset:
               radioAsset.setSelected(true);
               break;
       }
       txtMM.setText(String.valueOf(modul.getMm()));
       comboLocation.setSelectedItem(modul.getLocation());      
        
    }

    private void fillCombo() throws Exception {
        List<Location> locations = locationRepository.getAll(Sort.site_code);
        
        for (Location l: locations) {
            comboLocation.addItem(l);
        }
    }
}
